# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "rss"
name = "RSS"
url = "/index.xml"
[main.params]
icon = "rss"
newtab = true


[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/SqlDbaWithABeard"

[social.params]
icon = "brand-github"

[[social]]
identifier = "githubjr"
name = "GitHubJR"
url = "https://github.com/JessandRob"

[social.params]
icon = "brand-github"


[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://tech.lgbt/@robsewell"

[social.params]
icon = "brand-mastodon"

[[social]]
identifier = "bluesky"
name = "BlueSky"
url = "https://bsky.app/profile/robsewell.bsky.social"

[social.params]
icon = "brand-mastodon"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/robmsewell/"

[social.params]
icon = "brand-linkedin"
